<?php get_header();
require('template-parts/hero.php');
require('template-parts/intro-section.php');
require('template-parts/our-partners-slider.php');
// require('template-parts/products-section.php');
require('template-parts/products-v2-section.php');
require('template-parts/industries-section.php');
// require('template-parts/our-blogs-section.php');
require('template-parts/cta-contact.php');
get_footer();
